package com.zheng.pojo;

public class Topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.tagName
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    private String tagname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.name
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.url
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.weight
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.note
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.tagName
     *
     * @return the value of topic.tagName
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    public String getTagname() {
        return tagname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.tagName
     *
     * @param tagname the value for topic.tagName
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    public void setTagname(String tagname) {
        this.tagname = tagname == null ? null : tagname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.name
     *
     * @return the value of topic.name
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.name
     *
     * @param name the value for topic.name
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.url
     *
     * @return the value of topic.url
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.url
     *
     * @param url the value for topic.url
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.weight
     *
     * @return the value of topic.weight
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.weight
     *
     * @param weight the value for topic.weight
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.note
     *
     * @return the value of topic.note
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.note
     *
     * @param note the value for topic.note
     *
     * @mbggenerated Thu Jul 14 09:44:43 CST 2022
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}